# Generated by Django 2.1 on 2018-08-28 19:16

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Proposicao',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('id_ext', models.IntegerField()),
                ('numero', models.IntegerField()),
                ('sigla_tipo', models.CharField(max_length=3)),
                ('ementa', models.TextField(blank=True)),
                ('justificativa', models.TextField(blank=True)),
                ('data_apresentacao', models.DateField(null=True)),
            ],
        ),
    ]
