# Compose used as base for dev and prod

version: '3.5'

services:    

  db:
    image: postgres:10.5-alpine
    container_name: dbapi
    volumes:
      - postgres_data:/var/lib/postgresql/data/
      - backup_data:/backup_data/

volumes:
  postgres_data:
  backup_data:
    name: backup_data
