# Generated by Django 2.1.3 on 2018-12-03 18:08

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='EtapaProposicao',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('id_ext', models.IntegerField(help_text='Id externo do sistema da casa.', verbose_name='ID Externo')),
                ('numero', models.IntegerField(help_text='Número da proposição naquele ano e casa.', verbose_name='Número')),
                ('sigla_tipo', models.CharField(help_text='Sigla do tipo da proposição (PL, PLS etc)', max_length=3, verbose_name='Sigla do Tipo')),
                ('data_apresentacao', models.DateField(verbose_name='Data de apresentação')),
                ('casa', models.CharField(choices=[('camara', 'camara'), ('senado', 'senado')], help_text='Casa desta proposição.', max_length=6)),
                ('regime_tramitacao', models.CharField(choices=[('ordinario', 'ordinario'), ('prioridade', 'prioridade'), ('urgencia', 'urgencia')], max_length=10, null=True, verbose_name='Regime de tramitação')),
                ('forma_apreciacao', models.CharField(choices=[('conclusiva', 'conclusiva'), ('plenario', 'plenario')], max_length=10, null=True, verbose_name='Forma de Apreciação')),
                ('ementa', models.TextField(blank=True)),
                ('justificativa', models.TextField(blank=True)),
                ('palavras_chave', models.TextField(blank=True)),
                ('autor_nome', models.TextField(blank=True)),
                ('relator_nome', models.TextField(blank=True)),
                ('temperatura', models.FloatField(null=True)),
                ('em_pauta', models.NullBooleanField(help_text='TRUE se a proposicao estará em pauta na semana, FALSE caso contrario')),
                ('apelido', models.TextField(help_text='Apelido dado para proposição.', null=True, verbose_name='Apelido da proposição.')),
                ('tema', models.TextField(help_text='Podendo ser entre Meio Ambiente e agenda nacional.', max_length=40, null=True, verbose_name='Tema da proposição.')),
            ],
            options={
                'ordering': ('data_apresentacao',),
            },
        ),
        migrations.CreateModel(
            name='PautaHistorico',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('data', models.DateField(verbose_name='data')),
                ('semana', models.IntegerField(verbose_name='semana')),
                ('local', models.TextField(blank=True)),
                ('em_pauta', models.NullBooleanField(help_text='TRUE se a proposicao estiver em pauta, FALSE caso contrario')),
                ('proposicao', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='pauta_historico', to='api.EtapaProposicao')),
            ],
            options={
                'ordering': ('-data',),
                'get_latest_by': '-data',
            },
        ),
        migrations.CreateModel(
            name='Progresso',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('local_casa', models.CharField(help_text='Casa desta proposição.', max_length=30, null=True)),
                ('fase_global', models.TextField(blank=True)),
                ('local', models.TextField(blank=True, null=True)),
                ('data_inicio', models.DateField(blank=True, null=True, verbose_name='Data de início')),
                ('data_fim', models.DateField(blank=True, null=True, verbose_name='Data final')),
                ('pulou', models.NullBooleanField(help_text='TRUE se a proposicao pulou a fase, FALSE caso contrario')),
            ],
        ),
        migrations.CreateModel(
            name='Proposicao',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('apelido', models.TextField(blank=True)),
                ('tema', models.TextField(blank=True)),
            ],
        ),
        migrations.CreateModel(
            name='TemperaturaHistorico',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('periodo', models.DateField(verbose_name='periodo')),
                ('temperatura_periodo', models.IntegerField(help_text='Quantidade de eventos no período (semana).')),
                ('temperatura_recente', models.FloatField(help_text='Temperatura acumulada com decaimento exponencial.')),
                ('proposicao', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='temperatura_historico', to='api.EtapaProposicao')),
            ],
            options={
                'ordering': ('-periodo',),
                'get_latest_by': '-periodo',
            },
        ),
        migrations.CreateModel(
            name='TramitacaoEvent',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('data', models.DateField(verbose_name='Data')),
                ('sequencia', models.IntegerField(help_text='Sequência desse evento na lista de tramitações.', verbose_name='Sequência')),
                ('texto', models.TextField()),
                ('sigla_local', models.TextField()),
                ('situacao', models.TextField()),
                ('proposicao', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='tramitacao', to='api.EtapaProposicao')),
            ],
            options={
                'ordering': ('sequencia',),
            },
        ),
        migrations.AddField(
            model_name='progresso',
            name='proposicao',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='progresso', to='api.Proposicao'),
        ),
        migrations.AddField(
            model_name='etapaproposicao',
            name='proposicao',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='etapas', to='api.Proposicao'),
        ),
        migrations.AddIndex(
            model_name='etapaproposicao',
            index=models.Index(fields=['casa', 'id_ext'], name='api_etapapr_casa_a8605f_idx'),
        ),
    ]
