# Generated by Django 2.1 on 2018-08-29 13:33

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Proposicao',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('id_ext', models.IntegerField(help_text='Id externo do sistema da casa.', verbose_name='ID Externo')),
                ('numero', models.IntegerField(help_text='Número da proposição naquele ano e casa.', verbose_name='Número')),
                ('sigla_tipo', models.CharField(help_text='Sigla do tipo da proposição (PL, PLS etc)', max_length=3, verbose_name='Sigla do Tipo')),
                ('data_apresentacao', models.DateField(verbose_name='Data de apresentação')),
                ('casa', models.CharField(choices=[('camara', 'camara'), ('senado', 'senado')], help_text='Casa desta proposição.', max_length=6)),
                ('regime_tramitacao', models.CharField(choices=[('ordinario', 'ordinario'), ('prioridade', 'prioridade'), ('urgencia', 'urgencia')], max_length=10, null=True, verbose_name='Regime de tramitação')),
                ('forma_apreciacao', models.CharField(choices=[('conclusiva', 'conclusiva'), ('plenario', 'plenario')], max_length=10, null=True, verbose_name='Forma de Apreciação')),
                ('ementa', models.TextField(blank=True)),
                ('justificativa', models.TextField(blank=True)),
            ],
        ),
        migrations.AddIndex(
            model_name='proposicao',
            index=models.Index(fields=['casa', 'id_ext'], name='api_proposi_casa_ef16f9_idx'),
        ),
    ]
