# Generated by Django 2.1 on 2018-09-05 11:54

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_tramitacaoevent'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tramitacaoevent',
            name='proposicao',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='tramitacao', to='api.Proposicao'),
        ),
    ]
