# Generated by Django 2.1.1 on 2018-09-10 16:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0007_proposicao_autor_nome'),
    ]

    operations = [
        migrations.AddField(
            model_name='proposicao',
            name='energia',
            field=models.FloatField(null=True),
        ),
    ]
