# Generated by Django 2.1.1 on 2018-09-13 16:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0009_proposicao_em_pauta'),
    ]

    operations = [
        migrations.AddField(
            model_name='proposicao',
            name='apelido',
            field=models.CharField(help_text='Apelido dado para proposição.', max_length=60, null=True, verbose_name='Apelido da proposição.'),
        ),
    ]
