# Generated by Django 2.1.1 on 2018-09-13 19:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0010_proposicao_apelido'),
    ]

    operations = [
        migrations.AddField(
            model_name='proposicao',
            name='tema',
            field=models.TextField(help_text='Podendo ser entre Meio Ambiente e agenda nacional.', max_length=40, null=True, verbose_name='Tema da proposição.'),
        ),
    ]
