# Generated by Django 2.1.1 on 2018-09-25 13:36

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0011_proposicao_tema'),
    ]

    operations = [
        migrations.CreateModel(
            name='EnergiaRecentePeriodo',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('id_ext', models.IntegerField(help_text='Id externo do sistema da casa.', verbose_name='ID Externo')),
                ('casa', models.CharField(choices=[('camara', 'camara'), ('senado', 'senado')], help_text='Casa desta proposição.', max_length=6)),
                ('periodo', models.DateTimeField(verbose_name='Data')),
                ('energia_periodo', models.IntegerField()),
                ('energia_recente', models.FloatField()),
            ],
            options={
                'ordering': ('periodo',),
            },
        ),
        migrations.AlterField(
            model_name='proposicao',
            name='em_pauta',
            field=models.NullBooleanField(help_text='TRUE se a proposicao estará em pauta na semana, FALSE caso contrario'),
        ),
        migrations.AddField(
            model_name='energiarecenteperiodo',
            name='proposicao',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='energia_recente_periodo', to='api.Proposicao'),
        ),
    ]
