# Generated by Django 2.1.1 on 2018-09-24 19:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0011_proposicao_tema'),
    ]

    operations = [
        migrations.CreateModel(
            name='Progresso',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('id_ext', models.IntegerField(help_text='Id externo do sistema da casa.', verbose_name='ID Externo')),
                ('casa', models.CharField(choices=[('camara', 'camara'), ('senado', 'senado')], help_text='Casa desta proposição.', max_length=6)),
                ('fase_global', models.TextField(blank=True)),
                ('local', models.TextField(blank=True)),
                ('data_inicio', models.DateField(blank=True, verbose_name='Data de início')),
                ('data_fim', models.DateField(blank=True, verbose_name='Data final')),
            ],
            options={
                'ordering': ('data_inicio',),
            },
        ),
        migrations.AlterField(
            model_name='proposicao',
            name='em_pauta',
            field=models.NullBooleanField(help_text='TRUE se a proposicao estará em pauta na semana, FALSE caso contrario'),
        ),
    ]
