# Generated by Django 2.1.1 on 2018-09-27 19:42

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0011_proposicao_tema'),
    ]

    operations = [
        migrations.CreateModel(
            name='EnergiaHistorico',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('periodo', models.DateField(verbose_name='periodo')),
                ('energia_periodo', models.IntegerField(help_text='Quantidade de eventos no período (semana).')),
                ('energia_recente', models.FloatField(help_text='Energia acumulada com decaimento exponencial.')),
            ],
            options={
                'ordering': ('-periodo',),
                'get_latest_by': '-periodo',
            },
        ),
        migrations.CreateModel(
            name='Progresso',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('local_casa', models.CharField(help_text='Casa desta proposição.', max_length=6, null=True)),
                ('fase_global', models.TextField(blank=True)),
                ('local', models.TextField(blank=True)),
                ('data_inicio', models.DateField(null=True, verbose_name='Data de início')),
                ('data_fim', models.DateField(null=True, verbose_name='Data final')),
            ],
            options={
                'ordering': ('data_inicio',),
            },
        ),
        migrations.AlterField(
            model_name='proposicao',
            name='em_pauta',
            field=models.NullBooleanField(help_text='TRUE se a proposicao estará em pauta na semana, FALSE caso contrario'),
        ),
        migrations.AddField(
            model_name='progresso',
            name='proposicao',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='progresso', to='api.Proposicao'),
        ),
        migrations.AddField(
            model_name='energiahistorico',
            name='proposicao',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='energia_historico', to='api.Proposicao'),
        ),
    ]
