# Generated by Django 2.1.1 on 2018-09-13 17:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0011_remove_proposicao_apelido'),
    ]

    operations = [
        migrations.AddField(
            model_name='proposicao',
            name='tema',
            field=models.TextField(blank=True),
        ),
    ]
