# Generated by Django 2.1.1 on 2018-10-02 12:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0012_auto_20180927_1942'),
    ]

    operations = [
        migrations.AlterField(
            model_name='progresso',
            name='data_fim',
            field=models.DateField(default='2001-01-01', null=True, verbose_name='Data final'),
        ),
        migrations.AlterField(
            model_name='progresso',
            name='data_inicio',
            field=models.DateField(default='2000-01-01', null=True, verbose_name='Data de início'),
        ),
        migrations.AlterField(
            model_name='progresso',
            name='local',
            field=models.TextField(blank=True, null=True),
        ),
    ]
