# Generated by Django 2.1.2 on 2018-10-08 12:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0012_auto_20180927_1942'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Proposicao',
            new_name='EtapaProposicao',
        ),
        migrations.RemoveIndex(
            model_name='etapaproposicao',
            name='api_proposi_casa_ef16f9_idx',
        ),
        migrations.AddIndex(
            model_name='etapaproposicao',
            index=models.Index(fields=['casa', 'id_ext'], name='api_etapapr_casa_a8605f_idx'),
        ),
    ]
