# Generated by Django 2.1.1 on 2018-09-26 15:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0012_auto_20180924_1918'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Progresso',
        ),
    ]
