# Generated by Django 2.1.1 on 2018-10-02 13:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0013_auto_20181002_1203'),
    ]

    operations = [
        migrations.AlterField(
            model_name='progresso',
            name='data_fim',
            field=models.DateField(blank=True, default='2001-01-01', null=True, verbose_name='Data final'),
        ),
        migrations.AlterField(
            model_name='progresso',
            name='data_inicio',
            field=models.DateField(blank=True, default='2000-01-01', null=True, verbose_name='Data de início'),
        ),
    ]
