# Generated by Django 2.1.1 on 2018-09-26 16:24

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0013_delete_progresso'),
    ]

    operations = [
        migrations.CreateModel(
            name='Progresso',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fase_global', models.TextField(blank=True)),
                ('local', models.TextField(blank=True)),
                ('data_inicio', models.DateField(blank=True, verbose_name='Data de início')),
                ('data_fim', models.DateField(blank=True, verbose_name='Data final')),
                ('proposicao', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='progresso', to='api.Proposicao')),
            ],
            options={
                'ordering': ('data_inicio',),
            },
        ),
    ]
