# Generated by Django 2.1.1 on 2018-09-26 18:58

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0013_auto_20180925_1440'),
    ]

    operations = [
        migrations.CreateModel(
            name='EnergiaHistorico',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('periodo', models.DateField(verbose_name='periodo')),
                ('energia_periodo', models.IntegerField(help_text='Quantidade de eventos no período (semana)')),
                ('energia_recente', models.FloatField(help_text='Energia acumulada com decaimento exponencial')),
                ('proposicao', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='energia_historico', to='api.Proposicao')),
            ],
            options={
                'ordering': ('periodo',),
            },
        ),
        migrations.RemoveField(
            model_name='energiarecenteperiodo',
            name='proposicao',
        ),
        migrations.DeleteModel(
            name='EnergiaRecentePeriodo',
        ),
    ]
