# Generated by Django 2.1.1 on 2018-09-26 16:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0014_progresso'),
    ]

    operations = [
        migrations.AddField(
            model_name='progresso',
            name='casa',
            field=models.CharField(choices=[('camara', 'camara'), ('senado', 'senado')], help_text='Casa desta proposição.', max_length=6, null=True),
        ),
    ]
