# Generated by Django 2.1.1 on 2018-09-26 19:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0014_auto_20180926_1858'),
    ]

    operations = [
        migrations.AlterField(
            model_name='energiahistorico',
            name='energia_periodo',
            field=models.IntegerField(help_text='Quantidade de eventos no período (semana).'),
        ),
        migrations.AlterField(
            model_name='energiahistorico',
            name='energia_recente',
            field=models.FloatField(help_text='Energia acumulada com decaimento exponencial.'),
        ),
    ]
