# Generated by Django 2.1.1 on 2018-09-26 18:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0015_progresso_casa'),
    ]

    operations = [
        migrations.RenameField(
            model_name='progresso',
            old_name='casa',
            new_name='local_casa',
        ),
    ]
