# Generated by Django 2.1.1 on 2018-09-27 13:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0016_auto_20180926_2023'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='energiahistorico',
            options={'get_latest_by': '-periodo', 'ordering': ('-periodo',)},
        ),
    ]
