# Generated by Django 2.1.1 on 2018-09-27 12:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0016_auto_20180926_1813'),
    ]

    operations = [
        migrations.AlterField(
            model_name='progresso',
            name='data_fim',
            field=models.DateField(null=True, verbose_name='Data final'),
        ),
        migrations.AlterField(
            model_name='progresso',
            name='data_inicio',
            field=models.DateField(null=True, verbose_name='Data de início'),
        ),
        migrations.AlterField(
            model_name='progresso',
            name='local_casa',
            field=models.CharField(help_text='Casa desta proposição.', max_length=6, null=True),
        ),
    ]
