# Generated by Django 2.1.2 on 2018-10-30 11:58

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0016_auto_20181017_1205'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='progresso',
            name='etapa',
        ),
        migrations.AddField(
            model_name='progresso',
            name='proposicao',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, related_name='progresso', to='api.Proposicao'),
            preserve_default=False,
        ),
    ]
