# Generated by Django 2.1.1 on 2018-09-27 12:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0017_auto_20180927_1223'),
    ]

    operations = [
        migrations.AlterField(
            model_name='progresso',
            name='local_casa',
            field=models.CharField(choices=[('camara', 'camara'), ('senado', 'senado')], help_text='Casa desta proposição.', max_length=6, null=True),
        ),
    ]
