# Generated by Django 2.1.3 on 2018-11-14 13:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0018_auto_20181030_1446'),
    ]

    operations = [
        migrations.AddField(
            model_name='etapaproposicao',
            name='relator_nome',
            field=models.TextField(blank=True),
        ),
    ]
