# Generated by Django 2.1.3 on 2018-11-15 17:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0019_etapaproposicao_relator_nome'),
    ]

    operations = [
        migrations.AlterField(
            model_name='progresso',
            name='local_casa',
            field=models.CharField(help_text='Casa desta proposição.', max_length=30, null=True),
        ),
    ]
