# Generated by Django 2.1.3 on 2018-11-19 11:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0020_auto_20181115_1731'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='progresso',
            options={},
        ),
    ]
