# Generated by Django 2.1.3 on 2018-11-23 16:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0022_pautahistorico'),
    ]

    operations = [
        migrations.AddField(
            model_name='tramitacaoevent',
            name='local',
            field=models.TextField(default=''),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='tramitacaoevent',
            name='sigla_local',
            field=models.TextField(blank=True),
        ),
    ]
