# Generated by Django 2.1.3 on 2018-11-26 20:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0022_pautahistorico'),
    ]

    operations = [
        migrations.AddField(
            model_name='pautahistorico',
            name='semana',
            field=models.IntegerField(default=-1, verbose_name='semana'),
            preserve_default=False,
        ),
    ]
