# Generated by Django 2.1.3 on 2018-11-21 14:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0022_pautahistorico'),
    ]

    operations = [
        migrations.AddField(
            model_name='pautahistorico',
            name='id_ext',
            field=models.IntegerField(default=1, help_text='Id externo do sistema da casa.', verbose_name='ID Externo'),
            preserve_default=False,
        ),
    ]
