# Generated by Django 2.1.3 on 2018-11-21 14:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0023_pautahistorico_id_ext'),
    ]

    operations = [
        migrations.AddField(
            model_name='pautahistorico',
            name='casa',
            field=models.TextField(blank=True),
        ),
    ]
