# Generated by Django 2.1.3 on 2018-11-27 21:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0023_auto_20181123_1640'),
        ('api', '0023_pautahistorico_semana'),
    ]

    operations = [
    ]
