# Generated by Django 2.1.3 on 2018-11-30 23:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0023_pautahistorico_semana'),
    ]

    operations = [
        migrations.AlterField(
            model_name='etapaproposicao',
            name='apelido',
            field=models.TextField(help_text='Apelido dado para proposição.', null=True, verbose_name='Apelido da proposição.'),
        ),
    ]
