# Generated by Django 2.1.3 on 2018-12-04 11:25

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0024_auto_20181130_2318'),
    ]

    operations = [
        migrations.CreateModel(
            name='TemperaturaHistorico',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('periodo', models.DateField(verbose_name='periodo')),
                ('temperatura_periodo', models.IntegerField(help_text='Quantidade de eventos no período (semana).')),
                ('temperatura_recente', models.FloatField(help_text='Temperatura acumulada com decaimento exponencial.')),
            ],
            options={
                'ordering': ('-periodo',),
                'get_latest_by': '-periodo',
            },
        ),
        migrations.RemoveField(
            model_name='energiahistorico',
            name='proposicao',
        ),
        migrations.RenameField(
            model_name='etapaproposicao',
            old_name='energia',
            new_name='temperatura',
        ),
        migrations.DeleteModel(
            name='EnergiaHistorico',
        ),
        migrations.AddField(
            model_name='temperaturahistorico',
            name='proposicao',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='temperatura_historico', to='api.EtapaProposicao'),
        ),
    ]
