# Generated by Django 2.1.4 on 2018-12-11 14:33

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0024_auto_20181130_2318'),
    ]

    operations = [
        migrations.CreateModel(
            name='Emendas',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('data_apresentacao', models.DateField(verbose_name='data')),
                ('local', models.TextField(blank=True)),
                ('autor', models.TextField(blank=True)),
                ('proposicao', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='emendas', to='api.EtapaProposicao')),
            ],
            options={
                'ordering': ('-data_apresentacao',),
                'get_latest_by': '-data_apresentacao',
            },
        ),
    ]
