# Generated by Django 2.1.4 on 2018-12-17 12:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0026_emendas'),
    ]

    operations = [
        migrations.AddField(
            model_name='tramitacaoevent',
            name='evento',
            field=models.TextField(default=''),
            preserve_default=False,
        ),
    ]
