# Generated by Django 2.1.4 on 2018-12-17 17:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0026_emendas'),
    ]

    operations = [
        migrations.AddField(
            model_name='tramitacaoevent',
            name='local',
            field=models.TextField(default=''),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='tramitacaoevent',
            name='sigla_local',
            field=models.TextField(blank=True),
        ),
    ]
