# Generated by Django 2.1.3 on 2018-12-17 14:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0027_tramitacaoevent_evento'),
    ]

    operations = [
        migrations.AddField(
            model_name='tramitacaoevent',
            name='texto_tramitacao',
            field=models.TextField(default=''),
            preserve_default=False,
        ),
    ]
