# Generated by Django 2.1.3 on 2019-02-16 18:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0031_infogerais'),
    ]

    operations = [
        migrations.AddField(
            model_name='tramitacaoevent',
            name='status',
            field=models.TextField(default=''),
            preserve_default=False,
        ),
    ]
