# Generated by Django 2.1.3 on 2019-02-26 11:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0032_tramitacaoevent_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='etapaproposicao',
            name='casa_origem',
            field=models.TextField(blank=True),
        ),
    ]
