# Generated by Django 2.1.7 on 2019-03-01 13:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0033_etapaproposicao_casa_origem'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='tramitacaoevent',
            options={'ordering': ('data', 'sequencia')},
        ),
    ]
