# Generated by Django 2.1.3 on 2019-03-08 21:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0034_auto_20190301_1319'),
    ]

    operations = [
        migrations.AddField(
            model_name='tramitacaoevent',
            name='link_inteiro_teor',
            field=models.TextField(blank=True, null=True),
        ),
    ]
