# Generated by Django 2.1.7 on 2019-03-13 20:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0035_tramitacaoevent_link_inteiro_teor'),
    ]

    operations = [
        migrations.CreateModel(
            name='Comissao',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cargo', models.TextField(blank=True, help_text='Cargo ocupado pelo parlamentar na comissão', null=True)),
                ('id_comissao', models.IntegerField(help_text='Id da comissão')),
                ('partido', models.TextField(blank=True, help_text='Partido do parlamentar', null=True)),
                ('uf', models.TextField(blank=True, help_text='Estado do parlamentar', null=True)),
                ('situacao', models.TextField(blank=True, help_text='Titular ou suplente', null=True)),
                ('nome', models.TextField(blank=True, help_text='Nome do parlamentar', null=True)),
                ('sigla', models.TextField(help_text='Sigla da comissão')),
                ('casa', models.TextField(help_text='Camara ou Senado')),
            ],
        ),
    ]
