# Generated by Django 2.1.7 on 2019-03-13 20:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0036_comissao'),
    ]

    operations = [
        migrations.AlterField(
            model_name='comissao',
            name='id_comissao',
            field=models.IntegerField(blank=True, help_text='Id da comissão', null=True),
        ),
    ]
