# Generated by Django 2.1.7 on 2019-03-13 20:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0037_auto_20190313_2006'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='comissao',
            name='id_comissao',
        ),
    ]
