# Generated by Django 2.1.7 on 2019-03-18 12:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0038_remove_comissao_id_comissao'),
    ]

    operations = [
        migrations.AddField(
            model_name='tramitacaoevent',
            name='nivel',
            field=models.IntegerField(blank=True, help_text='Nível de importância deste evento para notificações.', null=True),
        ),
    ]
