# Generated by Django 2.1.7 on 2019-03-19 14:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0039_tramitacaoevent_nivel'),
    ]

    operations = [
        migrations.RenameField(
            model_name='tramitacaoevent',
            old_name='proposicao',
            new_name='etapa_proposicao',
        ),
    ]
