# Generated by Django 2.1.7 on 2019-03-19 19:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0040_auto_20190319_1409'),
    ]

    operations = [
        migrations.AddField(
            model_name='comissao',
            name='id_parlamentar',
            field=models.TextField(blank=True, help_text='Id do parlamentar', null=True),
        ),
    ]
