# Generated by Django 2.1.7 on 2019-03-20 12:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0041_comissao_id_parlamentar'),
    ]

    operations = [
        migrations.AddField(
            model_name='comissao',
            name='foto',
            field=models.TextField(blank=True, help_text='Foto do parlamentar', null=True),
        ),
    ]
