# Generated by Django 2.1.7 on 2019-03-27 19:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0042_comissao_foto'),
    ]

    operations = [
        migrations.AddField(
            model_name='emendas',
            name='inteiro_teor',
            field=models.TextField(blank=True, null=True),
        ),
    ]
