# Generated by Django 2.1.3 on 2019-04-04 19:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0043_emendas_inteiro_teor'),
    ]

    operations = [
        migrations.AddField(
            model_name='tramitacaoevent',
            name='tipo_documento',
            field=models.TextField(default=''),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='tramitacaoevent',
            name='titulo_evento',
            field=models.TextField(default=''),
            preserve_default=False,
        ),
    ]
