# Generated by Django 2.1.3 on 2019-04-11 17:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0043_emendas_inteiro_teor'),
    ]

    operations = [
        migrations.AddField(
            model_name='etapaproposicao',
            name='autor_partido',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='etapaproposicao',
            name='autor_uf',
            field=models.TextField(blank=True),
        ),
    ]
