# Generated by Django 2.1.7 on 2019-04-12 10:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0044_auto_20190404_1942'),
    ]

    operations = [
        migrations.AddField(
            model_name='emendas',
            name='codigo_emenda',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='emendas',
            name='distancia',
            field=models.FloatField(null=True),
        ),
        migrations.AddField(
            model_name='emendas',
            name='numero',
            field=models.IntegerField(default=0),
            preserve_default=False,
        ),
    ]
