# Generated by Django 2.1.7 on 2019-04-24 14:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0046_emendas_tipo_documento'),
    ]

    operations = [
        migrations.AddField(
            model_name='pautahistorico',
            name='hora',
            field=models.TextField(default='', verbose_name='hora'),
            preserve_default=False,
        ),
    ]
