# Generated by Django 2.1.7 on 2019-04-26 16:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0048_remove_pautahistorico_hora'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pautahistorico',
            name='data',
            field=models.DateTimeField(verbose_name='data'),
        ),
    ]
