# Generated by Django 2.1.7 on 2019-05-02 12:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0048_remove_pautahistorico_hora'),
    ]

    operations = [
        migrations.AddField(
            model_name='etapaproposicao',
            name='autor_partido',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='etapaproposicao',
            name='autor_uf',
            field=models.TextField(blank=True),
        ),
        migrations.AlterField(
            model_name='pautahistorico',
            name='data',
            field=models.DateTimeField(verbose_name='data'),
        ),
    ]
