# Generated by Django 2.1.7 on 2019-06-11 19:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0049_auto_20190502_1236'),
    ]

    operations = [
        migrations.AddField(
            model_name='etapaproposicao',
            name='ano',
            field=models.IntegerField(default=0, help_text='Ano da proposição.', verbose_name='Ano'),
            preserve_default=False,
        ),
    ]
