# Generated by Django 2.1.3 on 2019-05-01 14:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0049_auto_20190426_1647'),
    ]

    operations = [
        migrations.AddField(
            model_name='etapaproposicao',
            name='autor_partido',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='etapaproposicao',
            name='autor_uf',
            field=models.TextField(blank=True),
        ),
    ]
