# Generated by Django 2.1.3 on 2019-06-26 20:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0049_auto_20190502_1236'),
    ]

    operations = [
        migrations.AlterField(
            model_name='emendas',
            name='numero',
            field=models.FloatField(),
        ),
    ]
