# Generated by Django 2.1.7 on 2019-07-08 18:16

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0050_auto_20190626_2027'),
    ]

    operations = [
        migrations.CreateModel(
            name='Atores',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('id_autor', models.IntegerField(verbose_name='Id do autor do documento')),
                ('nome_autor', models.TextField(verbose_name='Nome do autor do documento')),
                ('codTipo', models.IntegerField(verbose_name='Código do tipo do documento')),
                ('sigla_tipo', models.TextField(verbose_name='Sigla do documento')),
                ('descricao_tipo', models.TextField(verbose_name='Descrição do tipo do documento')),
                ('qtd_de_documentos', models.IntegerField(verbose_name='Quantidade de documentos feitas por um determinado autor')),
                ('proposicao', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='atores', to='api.EtapaProposicao')),
            ],
        ),
    ]
