# Generated by Django 2.2.1 on 2019-07-07 16:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0051_atores'),
    ]

    operations = [
        migrations.AlterField(
            model_name='atores',
            name='codTipo',
            field=models.FloatField(verbose_name='Código do tipo do documento'),
        ),
    ]
