# Generated by Django 2.1.7 on 2019-07-18 14:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0051_atores'),
    ]

    operations = [
        migrations.AlterField(
            model_name='atores',
            name='is_important',
            field=models.BooleanField(default=False, verbose_name='É uma comissão ou plenário'),
            preserve_default=False,
        ),
    ]
