# Generated by Django 2.1.3 on 2019-07-09 20:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0051_atores'),
    ]

    operations = [
        migrations.AlterField(
            model_name='atores',
            name='tipo_generico',
            field=models.TextField(verbose_name='Tipo do documento'),
        ),
    ]
