# Generated by Django 2.2.1 on 2019-07-10 16:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0052_auto_20190709_1941'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='atores',
            name='cod_tipo',
        ),
        migrations.RemoveField(
            model_name='atores',
            name='descricao_tipo',
        ),
        migrations.RemoveField(
            model_name='atores',
            name='sigla_tipo',
        ),
    ]
