# Generated by Django 2.2.3 on 2019-08-02 21:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0052_auto_20190802_1817'),
    ]

    operations = [
        migrations.AddField(
            model_name='atores',
            name='tipo_autor',
            field=models.TextField(default='nao-parlamentar', verbose_name='Tipo do autor'),
            preserve_default=False,
        ),
    ]
