# Generated by Django 2.1.3 on 2019-07-11 14:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0053_auto_20190710_1602'),
        ('api', '0052_auto_20190709_2048'),
    ]

    operations = [
    ]
