# Generated by Django 2.1.7 on 2019-08-16 18:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0054_pressao'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pressao',
            name='max_pressao_principal',
            field=models.FloatField(verbose_name='Pressão do nome formal e do apelido'),
        ),
        migrations.AlterField(
            model_name='pressao',
            name='max_pressao_rel',
            field=models.FloatField(verbose_name='Pressão dos termos relacionados'),
        ),
        migrations.AlterField(
            model_name='pressao',
            name='maximo_geral',
            field=models.FloatField(verbose_name='Pressão dos termos relacionados'),
        ),
    ]
