# Generated by Django 2.2.3 on 2019-09-02 18:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0055_auto_20190816_1828'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pressao',
            name='date',
            field=models.DateField(verbose_name='Data da pressão'),
        ),
        migrations.AlterField(
            model_name='pressao',
            name='maximo_geral',
            field=models.FloatField(verbose_name='Máximo entre a pressão princial e a pressão relacionados'),
        ),
    ]
