# Generated by Django 2.2.5 on 2019-09-27 14:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0055_auto_20190816_1828'),
    ]

    operations = [
        migrations.AddField(
            model_name='proposicao',
            name='advocacy_link',
            field=models.TextField(blank=True),
        ),
    ]
