# Generated by Django 2.2.6 on 2019-10-25 16:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0056_auto_20191008_1321'),
    ]

    operations = [
        migrations.CreateModel(
            name='Nodes',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('id_leggo', models.IntegerField(help_text='Id do leggo.')),
                ('index', models.IntegerField(verbose_name='index')),
                ('id_autor', models.IntegerField(help_text='Id do autor.')),
                ('nome', models.TextField(help_text='Nome do parlamentar.')),
                ('partido', models.TextField(help_text='Partido do parlamentar.')),
                ('uf', models.TextField(help_text='Uf do parlamentar.')),
                ('bancada', models.TextField(help_text='Bancada do parlamentar.')),
                ('nome_eleitoral', models.TextField(help_text='Nome eleitoral do parlamentar.')),
                ('node_size', models.FloatField(help_text='Tamanho do nó')),
            ],
        ),
    ]
