# Generated by Django 2.2.5 on 2019-09-17 11:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0056_auto_20190917_1141'),
    ]

    operations = [
        migrations.AddField(
            model_name='etapaproposicao',
            name='id_leggo',
            field=models.IntegerField(default=0, help_text='Id interto do leggo.', verbose_name='ID Leggo'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='proposicao',
            name='id_leggo',
            field=models.IntegerField(help_text='Id interno do leggo.', verbose_name='ID do Leggo'),
        ),
    ]
