# Generated by Django 2.2.5 on 2019-09-05 17:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0056_auto_20190902_1825'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pressao',
            name='date',
            field=models.DateField(verbose_name='Dia da popularidade'),
        ),
        migrations.AlterField(
            model_name='pressao',
            name='maximo_geral',
            field=models.FloatField(verbose_name='Pressão dos termos relacionados'),
        ),
    ]
