# Generated by Django 2.2.6 on 2019-10-25 16:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0057_nodes'),
    ]

    operations = [
        migrations.CreateModel(
            name='Edges',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('id_leggo', models.IntegerField(help_text='Id do leggo.')),
                ('source', models.IntegerField(help_text='Origem da aresta.')),
                ('target', models.IntegerField(help_text='Destino da aresta.')),
                ('value', models.TextField(help_text='Valor da aresta.')),
            ],
        ),
    ]
