# Generated by Django 2.2.6 on 2019-11-05 11:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0059_remove_nodes_index'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Edges',
            new_name='CoautoriaEdges',
        ),
        migrations.RenameModel(
            old_name='Nodes',
            new_name='CoautoriaNodes',
        ),
    ]
