# Generated by Django 2.2.6 on 2019-11-05 13:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0060_auto_20191105_1138'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='CoautoriaEdges',
            new_name='CoautoriaEdge',
        ),
        migrations.RenameModel(
            old_name='CoautoriaNodes',
            new_name='CoautoriaNode',
        ),
    ]
