# Generated by Django 2.2.6 on 2019-11-13 13:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0061_auto_20191105_1303'),
    ]

    operations = [
        migrations.CreateModel(
            name='Autoria',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('id_leggo', models.IntegerField(help_text='Id do leggo.')),
                ('id_documento', models.IntegerField(help_text='Id do documento.')),
                ('descricao_tipo_documento', models.TextField(help_text='Tipo do documento.')),
                ('id_autor', models.IntegerField(help_text='Id do autor.')),
                ('data', models.DateField(help_text='Data do documento.')),
                ('url_inteiro_teor', models.TextField(help_text='URL do documento.')),
                ('nome_eleitoral', models.TextField(help_text='Nome eleitoral do parlamentar.')),
            ],
        ),
    ]
