# Generated by Django 2.2.6 on 2019-11-11 16:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0062_auto_20191107_1809'),
    ]

    operations = [
        migrations.AddField(
            model_name='atores',
            name='bancada',
            field=models.TextField(default='', verbose_name='Bancada do ator'),
            preserve_default=False,
        ),
    ]
