# Generated by Django 2.2.6 on 2019-11-13 14:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0062_autoria'),
        ('api', '0063_atores_bancada'),
    ]

    operations = [
    ]
