# Generated by Django 2.2.6 on 2019-11-15 20:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0063_atores_bancada'),
    ]

    operations = [
        migrations.AddField(
            model_name='atores',
            name='id_leggo',
            field=models.IntegerField(default=-1, verbose_name='Id da proposição principal no leggo.'),
            preserve_default=False,
        ),
    ]
