# Generated by Django 2.2.6 on 2019-11-18 19:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0064_atores_id_leggo'),
    ]

    operations = [
        migrations.AddField(
            model_name='atores',
            name='casa',
            field=models.CharField(choices=[('camara', 'camara'), ('senado', 'senado')], default='', help_text='Casa desta proposição.', max_length=6),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='atores',
            name='id_ext',
            field=models.IntegerField(default=-1, help_text='Id externo do sistema da casa.', verbose_name='ID Externo'),
            preserve_default=False,
        ),
    ]
