# Generated by Django 2.2.6 on 2019-11-18 20:19

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0065_auto_20191118_1918'),
    ]

    operations = [
        migrations.AlterField(
            model_name='atores',
            name='proposicao',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='atores', to='api.Proposicao'),
        ),
    ]
