# Generated by Django 2.2.6 on 2019-11-19 14:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0066_auto_20191118_2019'),
    ]

    operations = [
        migrations.AddField(
            model_name='atores',
            name='num_documentos',
            field=models.IntegerField(default=0, verbose_name='Quantidade de documentos apresentada por um determinado autor'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='atores',
            name='peso_total_documentos',
            field=models.FloatField(verbose_name='Contribuição agregada de um determinado autor em documentos'),
        ),
    ]
