# Generated by Django 2.2.6 on 2019-11-19 20:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0064_merge_20191113_1408'),
        ('api', '0067_auto_20191119_1436'),
    ]

    operations = [
    ]
