# Generated by Django 2.2.7 on 2019-11-22 17:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0069_autoria_coautores'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='autoria',
            name='coautores',
        ),
        migrations.AddField(
            model_name='autoria',
            name='autores',
            field=models.TextField(default='', help_text='Todos autores de um documento.'),
            preserve_default=False,
        ),
    ]
