# Generated by Django 3.0 on 2019-12-09 12:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0069_autoria_coautores'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='autoria',
            name='coautores',
        ),
        migrations.AddField(
            model_name='autoria',
            name='autores',
            field=models.TextField(default='', help_text='Todos autores de um documento.'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='etapaproposicao',
            name='advocacy_link',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='proposicao',
            name='advocacy_link',
            field=models.TextField(blank=True, null=True),
        ),
    ]
