# Generated by Django 3.0 on 2019-12-16 16:41

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0070_auto_20191209_1236'),
    ]

    operations = [
        migrations.AddField(
            model_name='pressao',
            name='id_leggo',
            field=models.IntegerField(default=0, verbose_name='Id da proposição principal no leggo.'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='pressao',
            name='proposicao',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='pressao', to='api.Proposicao'),
        ),
    ]
