# Generated by Django 2.2.7 on 2019-11-27 14:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0070_auto_20191122_1734'),
        ('api', '0069_auto_20191125_1721'),
    ]

    operations = [
    ]
