# Generated by Django 3.0 on 2019-12-04 16:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0070_auto_20191122_1734'),
        ('api', '0069_auto_20191125_1721'),
        ('api', '0057_etapaproposicao_advocacy_link'),
    ]

    operations = [
    ]
