# Generated by Django 2.2.6 on 2019-11-29 19:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0057_etapaproposicao_advocacy_link'),
        ('api', '0070_auto_20191122_1734'),
    ]

    operations = [
    ]
