# Generated by Django 3.0 on 2019-12-09 13:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
	('api', '0069_auto_20191125_1721'),
        ('api', '0070_auto_20191209_1236'),
        ('api', '0057_etapaproposicao_advocacy_link'),
    ]

    operations = [
        migrations.AlterField(
            model_name='etapaproposicao',
            name='advocacy_link',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='proposicao',
            name='advocacy_link',
            field=models.TextField(blank=True, null=True),
        ),
    ]
