# Generated by Django 3.0.2 on 2020-03-20 14:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0071_auto_20191216_1641'),
    ]

    operations = [
        migrations.CreateModel(
            name='Interesse',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('id_ext', models.IntegerField(help_text='Id externo da proposição na casa correspondente.')),
                ('casa', models.TextField(help_text='Casa de tramitação da proposição.')),
                ('id_leggo', models.TextField(help_text='Id da proposição no Leggo.')),
                ('interesse', models.TextField(help_text='Interesse da PL')),
            ],
        ),
    ]
