# Generated by Django 2.2.6 on 2019-12-03 16:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0071_merge_20191129_1908'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='etapaproposicao',
            name='advocacy_link',
        ),
    ]
