# Generated by Django 3.0.4 on 2020-03-26 14:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0071_auto_20191216_1641'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='pressao',
            name='max_pressao_principal',
        ),
        migrations.RemoveField(
            model_name='pressao',
            name='max_pressao_rel',
        ),
        migrations.RemoveField(
            model_name='pressao',
            name='maximo_geral',
        ),
        migrations.AddField(
            model_name='pressao',
            name='casa',
            field=models.CharField(choices=[('camara', 'camara'), ('senado', 'senado')], default='', help_text='Casa.', max_length=6),
        ),
        migrations.AddField(
            model_name='pressao',
            name='id_ext',
            field=models.IntegerField(default=-1, help_text='Id externo do sistema da casa.', verbose_name='ID Externo'),
        ),
        migrations.AddField(
            model_name='pressao',
            name='popularity',
            field=models.FloatField(default=0, verbose_name='Pressão combinada do Twitter e Google Trends'),
        ),
        migrations.AddField(
            model_name='pressao',
            name='trends_max_popularity',
            field=models.FloatField(default=0, verbose_name='Pressão máxima entre os termos'),
        ),
        migrations.AddField(
            model_name='pressao',
            name='trends_max_pressao_principal',
            field=models.FloatField(default=0, verbose_name='Pressão do nome formal e do apelido'),
        ),
        migrations.AddField(
            model_name='pressao',
            name='trends_max_pressao_rel',
            field=models.FloatField(default=0, verbose_name='Pressão dos termos relacionados'),
        ),
        migrations.AddField(
            model_name='pressao',
            name='twitter_mean_popularity',
            field=models.FloatField(default=0, verbose_name='Pressão no twitter'),
        ),
    ]
