# Generated by Django 3.0.2 on 2020-03-26 17:15

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0071_auto_20191216_1641'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='etapaproposicao',
            name='advocacy_link',
        ),
        migrations.RemoveField(
            model_name='etapaproposicao',
            name='apelido',
        ),
        migrations.RemoveField(
            model_name='etapaproposicao',
            name='tema',
        ),
        migrations.RemoveField(
            model_name='proposicao',
            name='advocacy_link',
        ),
        migrations.RemoveField(
            model_name='proposicao',
            name='apelido',
        ),
        migrations.RemoveField(
            model_name='proposicao',
            name='tema',
        ),
        migrations.CreateModel(
            name='Interesse',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('id_leggo', models.IntegerField(help_text='Id da proposição no Leggo.')),
                ('interesse', models.TextField(help_text='Interesse da Proposição')),
                ('apelido', models.TextField(help_text='Apelido da Proposição')),
                ('tema', models.TextField(help_text='Temas da Proposição')),
                ('keywords', models.TextField(help_text='Conjunto de palavras-chave da Proposição')),
                ('advocacy_link', models.TextField(help_text='Link para conteúdo advocacy da Proposição')),
                ('tipo_agenda', models.TextField(help_text='Tipo da Agenda da Proposição')),
                ('proposicao', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='interesse', to='api.Proposicao')),
            ],
        ),
    ]
