# Generated by Django 3.0.4 on 2020-03-26 19:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0072_auto_20200326_1428'),
        ('api', '0072_interesse'),
    ]

    operations = [
    ]
