# Generated by Django 3.0.2 on 2020-03-24 17:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0072_interesse'),
    ]

    operations = [
        migrations.AddField(
            model_name='etapaproposicao',
            name='keywords',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='etapaproposicao',
            name='tipo_agenda',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='proposicao',
            name='keywords',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='proposicao',
            name='tipo_agenda',
            field=models.TextField(blank=True, null=True),
        ),
    ]
