# Generated by Django 3.0.2 on 2020-03-27 12:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0072_interesse'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='etapaproposicao',
            name='advocacy_link',
        ),
        migrations.RemoveField(
            model_name='etapaproposicao',
            name='apelido',
        ),
        migrations.RemoveField(
            model_name='etapaproposicao',
            name='tema',
        ),
        migrations.RemoveField(
            model_name='proposicao',
            name='advocacy_link',
        ),
        migrations.RemoveField(
            model_name='proposicao',
            name='apelido',
        ),
        migrations.RemoveField(
            model_name='proposicao',
            name='tema',
        ),
        migrations.AddField(
            model_name='interesse',
            name='advocacy_link',
            field=models.TextField(blank=True, help_text='Link para conteúdo advocacy da Proposição', null=True),
        ),
        migrations.AddField(
            model_name='interesse',
            name='apelido',
            field=models.TextField(blank=True, help_text='Apelido da Proposição', null=True),
        ),
        migrations.AddField(
            model_name='interesse',
            name='keywords',
            field=models.TextField(blank=True, help_text='Conjunto de palavras-chave da Proposição', null=True),
        ),
        migrations.AddField(
            model_name='interesse',
            name='tema',
            field=models.TextField(blank=True, help_text='Temas da Proposição', null=True),
        ),
        migrations.AddField(
            model_name='interesse',
            name='tipo_agenda',
            field=models.TextField(blank=True, help_text='Tipo da Agenda da Proposição', null=True),
        ),
        migrations.AlterField(
            model_name='interesse',
            name='interesse',
            field=models.TextField(blank=True, help_text='Interesse da Proposição', null=True),
        ),
    ]
