# Generated by Django 3.0 on 2019-12-03 17:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0072_remove_etapaproposicao_advocacy_link'),
    ]

    operations = [
        migrations.AlterField(
            model_name='proposicao',
            name='advocacy_link',
            field=models.TextField(blank=True, null=True),
        ),
    ]
