# Generated by Django 3.0.4 on 2020-04-02 14:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0074_auto_20200402_1207'),
    ]

    operations = [
        migrations.AddField(
            model_name='pressao',
            name='interesse',
            field=models.TextField(blank=True, help_text='Interesse da proposição', null=True),
        ),
    ]
