# Generated by Django 3.0.4 on 2020-04-02 17:55

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0075_pressao_interesse'),
    ]

    operations = [
        migrations.AddField(
            model_name='pressao',
            name='interesse_relacionado',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='pressaoInteresse', to='api.Interesse'),
        ),
    ]
