# Generated by Django 3.0.4 on 2020-04-20 17:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0076_pressao_interesse_relacionado'),
    ]

    operations = [
        migrations.AddField(
            model_name='interesse',
            name='nome_interesse',
            field=models.TextField(blank=True, help_text='Nome do Interesse da Proposição', null=True),
        ),
    ]
