# Generated by Django 3.0.4 on 2020-04-30 14:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0077_interesse_nome_interesse'),
    ]

    operations = [
        migrations.AlterField(
            model_name='emendas',
            name='autor',
            field=models.TextField(blank=True, help_text='Autor da emenda'),
        ),
        migrations.AlterField(
            model_name='emendas',
            name='codigo_emenda',
            field=models.TextField(blank=True, help_text='Código da emenda na casa correspondente'),
        ),
        migrations.AlterField(
            model_name='emendas',
            name='data_apresentacao',
            field=models.DateField(help_text='Data de apresentação da emenda', verbose_name='data'),
        ),
        migrations.AlterField(
            model_name='emendas',
            name='distancia',
            field=models.FloatField(help_text='Distância calculada entre a emenda e o texto original', null=True),
        ),
        migrations.AlterField(
            model_name='emendas',
            name='local',
            field=models.TextField(blank=True, help_text='Local de apresentação da emenda'),
        ),
        migrations.AlterField(
            model_name='emendas',
            name='numero',
            field=models.FloatField(help_text='Número da emenda'),
        ),
        migrations.AlterField(
            model_name='emendas',
            name='tipo_documento',
            field=models.TextField(help_text='Tipo de documento'),
        ),
    ]
