# Generated by Django 3.0.6 on 2020-05-22 14:20

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0078_auto_20200430_1436'),
    ]

    operations = [
        migrations.CreateModel(
            name='Anotacao',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('id_leggo', models.IntegerField(help_text='Id da proposição no Leggo')),
                ('data_criacao', models.DateField(help_text='Data de criação da anotação')),
                ('data_ultima_modificacao', models.DateField(help_text='Data de ultima modificação da anotação')),
                ('autor', models.TextField(blank=True, help_text='Autor da anotação', null=True)),
                ('titulo', models.TextField(blank=True, help_text='Título da anotação', null=True)),
                ('anotacao', models.TextField(blank=True, help_text='Conteúdo da anotação', null=True)),
                ('peso', models.IntegerField(help_text='Peso de importância da anotação')),
                ('interesse', models.TextField(blank=True, help_text='Interesse da anotação sobre a proposição', null=True)),
                ('proposicao', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='anotacao', to='api.Proposicao')),
            ],
        ),
    ]
