# Generated by Django 3.0.6 on 2020-05-25 19:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0079_anotacao'),
    ]

    operations = [
        migrations.AlterField(
            model_name='anotacao',
            name='data_criacao',
            field=models.DateTimeField(help_text='Data de criação da anotação'),
        ),
        migrations.AlterField(
            model_name='anotacao',
            name='data_ultima_modificacao',
            field=models.DateTimeField(help_text='Data de ultima modificação da anotação'),
        ),
    ]
