# Generated by Django 3.0.6 on 2020-05-27 12:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0080_auto_20200525_1919'),
    ]

    operations = [
        migrations.AddField(
            model_name='anotacao',
            name='categoria',
            field=models.TextField(blank=True, help_text='Categoria da anotação', null=True),
        ),
    ]
