# Generated by Django 3.0.7 on 2020-06-15 19:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0081_anotacao_categoria'),
    ]

    operations = [
        migrations.AddField(
            model_name='atores',
            name='casa_autor',
            field=models.TextField(help_text='Casa do autor do documento.', null=True),
        ),
        migrations.AddField(
            model_name='atores',
            name='id_autor_parlametria',
            field=models.IntegerField(help_text='Id do autor na plataforma parlametria.', null=True),
        ),
        migrations.AddField(
            model_name='autoria',
            name='casa',
            field=models.TextField(help_text='Casa de origem da proposição principal.', null=True),
        ),
        migrations.AddField(
            model_name='autoria',
            name='casa_autor',
            field=models.TextField(help_text='Casa do autor do documento.', null=True),
        ),
        migrations.AddField(
            model_name='autoria',
            name='id_autor_parlametria',
            field=models.IntegerField(help_text='Id do autor na plataforma parlametria.', null=True),
        ),
        migrations.AddField(
            model_name='autoria',
            name='id_principal',
            field=models.IntegerField(help_text='Id da proposição principal do documento.', null=True),
        ),
        migrations.AddField(
            model_name='coautorianode',
            name='casa_autor',
            field=models.TextField(help_text='Casa do autor.', null=True),
        ),
        migrations.AddField(
            model_name='coautorianode',
            name='id_autor_parlametria',
            field=models.IntegerField(help_text='Id do autor na plataforma parlametria.', null=True),
        ),
    ]
