# Generated by Django 3.0.7 on 2020-06-11 16:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0081_anotacao_categoria'),
    ]

    operations = [
        migrations.AlterField(
            model_name='atores',
            name='id_autor',
            field=models.IntegerField(verbose_name='Id do autor do documento'),
        ),
    ]
