# Generated by Django 3.0.7 on 2020-06-19 13:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0082_auto_20200615_1942'),
        ('api', '0082_auto_20200611_1641'),
    ]

    operations = [
    ]
