# Generated by Django 3.0.7 on 2020-06-16 19:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0082_auto_20200615_1942'),
    ]

    operations = [
        migrations.AddField(
            model_name='autoria',
            name='tipo_documento',
            field=models.TextField(help_text='Tipo geral do documento.', null=True),
        ),
    ]
