# Generated by Django 3.0.7 on 2020-06-22 18:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0083_autoria_tipo_documento'),
        ('api', '0083_merge_20200619_1338'),
    ]

    operations = [
    ]
