# Generated by Django 3.0.7 on 2020-06-24 16:08

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0083_autoria_tipo_documento'),
    ]

    operations = [
        migrations.CreateModel(
            name='AnotacaoGeral',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('data_criacao', models.DateTimeField(help_text='Data de criação da anotação')),
                ('data_ultima_modificacao', models.DateTimeField(help_text='Data de ultima modificação da anotação')),
                ('autor', models.TextField(blank=True, help_text='Autor da anotação', null=True)),
                ('categoria', models.TextField(blank=True, help_text='Categoria da anotação', null=True)),
                ('titulo', models.TextField(blank=True, help_text='Título da anotação', null=True)),
                ('anotacao', models.TextField(blank=True, help_text='Conteúdo da anotação', null=True)),
                ('peso', models.IntegerField(help_text='Peso de importância da anotação')),
                ('interesse', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='anotacao', to='api.Interesse')),
            ],
        ),
    ]
