# Generated by Django 3.0.7 on 2020-06-24 17:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0085_auto_20200624_1623'),
        ('api', '0084_merge_20200622_1840'),
    ]

    operations = [
    ]
