# Generated by Django 3.0.7 on 2020-07-13 12:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0086_merge_20200624_1737'),
    ]

    operations = [
        migrations.CreateModel(
            name='Entidade',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('legislatura', models.IntegerField(help_text='ID da legislatura da entidade')),
                ('id_entidade', models.IntegerField(help_text='ID da entidade (para os parlamentares, é o id real nas respectivas casas)')),
                ('id_entidade_parlametria', models.IntegerField(help_text='ID da entidade na plataforma Parlametria')),
                ('casa', models.TextField(help_text='Casa da entidade.')),
                ('nome', models.TextField(help_text='Nome da entidade')),
                ('sexo', models.TextField(help_text='Sexo da entidade', null=True)),
                ('partido', models.TextField(help_text='Sigla do partido da entidade', null=True)),
                ('uf', models.TextField(help_text='Sigla da uf da entidade', null=True)),
                ('situacao', models.TextField(help_text='Situação da entidade', null=True)),
                ('em_exercicio', models.IntegerField(help_text='Flag se a entidade está em exercício ou não', null=True)),
                ('is_parlamentar', models.IntegerField(help_text='Flag se a entidade é um parlamentar ou não')),
            ],
        ),
    ]
