# Generated by Django 3.0.7 on 2020-07-14 09:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0087_entidade'),
    ]

    operations = [
        migrations.AlterField(
            model_name='entidade',
            name='id_entidade',
            field=models.IntegerField(help_text='ID da entidade (para os parlamentares, é o id nas casas)'),
        ),
    ]
