# Generated by Django 3.0.7 on 2020-07-15 17:13

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0088_auto_20200714_0900'),
    ]

    operations = [
        migrations.CreateModel(
            name='AutoresProposicao',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('id_leggo', models.IntegerField(help_text='ID interno do Leggo')),
                ('id_camara', models.IntegerField(blank=True, default=None, help_text='Id externo do sistema da Câmara', null=True)),
                ('id_senado', models.IntegerField(blank=True, default=None, help_text='Id externo do sistema do Senado', null=True)),
                ('id_autor_parlametria', models.IntegerField(help_text='Id do autor no Parlametria')),
                ('id_autor', models.IntegerField(help_text='Id do autor na casa de origem.')),
                ('entidade', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='entidadeAutor', to='api.Entidade')),
                ('proposicao', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='autoresProposicao', to='api.Proposicao')),
            ],
        ),
    ]
