# Generated by Django 3.0.7 on 2020-07-20 17:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0087_autoria_peso_autor_documento'),
        ('api', '0089_autoresproposicao'),
    ]

    operations = [
    ]
