# Generated by Django 3.0.7 on 2020-07-22 18:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0090_merge_20200720_1716'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='atores',
            name='nome_autor',
        ),
        migrations.RemoveField(
            model_name='atores',
            name='partido',
        ),
        migrations.RemoveField(
            model_name='atores',
            name='uf',
        ),
    ]
