# Generated by Django 3.0.7 on 2020-07-28 10:24

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0090_merge_20200720_1716'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='etapaproposicao',
            name='relator_nome',
        ),
        migrations.AddField(
            model_name='etapaproposicao',
            name='relator_id',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='etapaproposicao',
            name='relator_id_parlametria',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='etapaproposicao',
            name='relatoria',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='relatoria', to='api.Entidade'),
        ),
    ]
