# Generated by Django 3.0.7 on 2020-07-21 20:44

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0090_merge_20200720_1716'),
    ]

    operations = [
        migrations.AddField(
            model_name='autoria',
            name='etapa_proposicao',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='autorias', to='api.EtapaProposicao'),
        ),
    ]
