# Generated by Django 3.0.7 on 2020-07-29 19:30

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0091_autoria_etapa_proposicao'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='atores',
            name='nome_autor',
        ),
        migrations.RemoveField(
            model_name='atores',
            name='partido',
        ),
        migrations.RemoveField(
            model_name='atores',
            name='uf',
        ),
        migrations.AddField(
            model_name='atores',
            name='entidade',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='entidadeAtor', to='api.Entidade'),
        ),
    ]
