# Generated by Django 3.0.7 on 2020-07-22 19:41

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0091_auto_20200722_1804'),
    ]

    operations = [
        migrations.AddField(
            model_name='atores',
            name='entidade',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='entidadeAtor', to='api.Entidade'),
        ),
    ]
