# Generated by Django 3.0.7 on 2020-07-29 15:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0091_autoria_etapa_proposicao'),
        ('api', '0091_auto_20200728_1024'),
    ]

    operations = [
    ]
