# Generated by Django 3.0.7 on 2020-07-30 17:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0092_auto_20200729_1930'),
    ]

    operations = [
        migrations.AddField(
            model_name='interesse',
            name='tema_slug',
            field=models.TextField(blank=True, help_text='Slug dos temas da Proposição', null=True),
        ),
    ]
