# Generated by Django 3.0.7 on 2020-08-06 10:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0092_merge_20200729_1502'),
        ('api', '0093_interesse_tema_slug'),
    ]

    operations = [
    ]
