# Generated by Django 3.1 on 2020-08-10 17:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0094_merge_20200806_1039'),
    ]

    operations = [
        migrations.AlterField(
            model_name='etapaproposicao',
            name='em_pauta',
            field=models.BooleanField(help_text='TRUE se a proposicao estará em pauta na semana, FALSE caso contrario', null=True),
        ),
        migrations.AlterField(
            model_name='infogerais',
            name='value',
            field=models.JSONField(),
        ),
        migrations.AlterField(
            model_name='pautahistorico',
            name='em_pauta',
            field=models.BooleanField(help_text='TRUE se a proposicao estiver em pauta, FALSE caso contrario', null=True),
        ),
        migrations.AlterField(
            model_name='progresso',
            name='pulou',
            field=models.BooleanField(help_text='TRUE se a proposicao pulou a fase, FALSE caso contrario', null=True),
        ),
    ]
