# Generated by Django 3.1 on 2020-08-11 08:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0095_auto_20200810_1745'),
    ]

    operations = [
        migrations.AlterField(
            model_name='etapaproposicao',
            name='relator_id',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='etapaproposicao',
            name='relator_id_parlametria',
            field=models.TextField(blank=True, null=True),
        ),
    ]
