# Generated by Django 3.1 on 2020-08-25 13:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0095_auto_20200810_1745'),
    ]

    operations = [
        migrations.AlterField(
            model_name='anotacao',
            name='id_leggo',
            field=models.TextField(help_text='Id da proposição no Leggo'),
        ),
        migrations.AlterField(
            model_name='atores',
            name='id_leggo',
            field=models.TextField(verbose_name='Id da proposição principal no leggo.'),
        ),
        migrations.AlterField(
            model_name='autoresproposicao',
            name='id_leggo',
            field=models.TextField(help_text='ID interno do Leggo'),
        ),
        migrations.AlterField(
            model_name='autoria',
            name='id_leggo',
            field=models.TextField(help_text='Id do leggo.'),
        ),
        migrations.AlterField(
            model_name='coautoriaedge',
            name='id_leggo',
            field=models.TextField(help_text='Id do leggo.'),
        ),
        migrations.AlterField(
            model_name='coautorianode',
            name='id_leggo',
            field=models.TextField(help_text='Id do leggo.'),
        ),
        migrations.AlterField(
            model_name='etapaproposicao',
            name='id_leggo',
            field=models.TextField(help_text='Id interno do leggo.', verbose_name='ID Leggo'),
        ),
        migrations.AlterField(
            model_name='interesse',
            name='id_leggo',
            field=models.TextField(help_text='Id da proposição no Leggo.'),
        ),
        migrations.AlterField(
            model_name='pressao',
            name='id_leggo',
            field=models.TextField(verbose_name='Id da proposição principal no leggo.'),
        ),
        migrations.AlterField(
            model_name='proposicao',
            name='id_leggo',
            field=models.TextField(help_text='Id interno do leggo.', verbose_name='ID do Leggo'),
        ),
    ]
