# Generated by Django 3.1 on 2020-08-11 10:46

import django.contrib.postgres.fields.jsonb
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0095_auto_20200810_1745'),
    ]

    operations = [
        migrations.AlterField(
            model_name='infogerais',
            name='value',
            field=django.contrib.postgres.fields.jsonb.JSONField(),
        ),
    ]
