# Generated by Django 3.1 on 2020-09-11 15:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0096_auto_20200825_1322'),
    ]

    operations = [
        migrations.AddField(
            model_name='atores',
            name='tipo_acao',
            field=models.TextField(help_text='Tipo de ação', null=True),
        ),
        migrations.AddField(
            model_name='autoria',
            name='tipo_acao',
            field=models.TextField(help_text='Tipo de ação', null=True),
        ),
    ]
