# Generated by Django 3.1 on 2020-10-05 12:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0097_auto_20200911_1526'),
    ]

    operations = [
        migrations.AddField(
            model_name='proposicao',
            name='sigla_camara',
            field=models.TextField(blank=True, null=True, verbose_name='Sigla da proposição na Câmara'),
        ),
        migrations.AddField(
            model_name='proposicao',
            name='sigla_senado',
            field=models.TextField(blank=True, null=True, verbose_name='Sigla da proposição no Senado'),
        ),
    ]
