# Generated by Django 3.0.7 on 2020-10-02 18:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0097_auto_20200911_1526'),
    ]

    operations = [
        migrations.AddField(
            model_name='etapaproposicao',
            name='status',
            field=models.TextField(blank=True, null=True),
        ),
    ]
