# Generated by Django 3.0.7 on 2020-10-15 12:43

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0099_etapaproposicao_status'),
    ]

    operations = [
        migrations.CreateModel(
            name='RelatoresProposicao',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('id_leggo', models.TextField(help_text='ID interno do Leggo')),
                ('id_ext', models.IntegerField(blank=True, default=None, help_text='Id externo da etapa da proposição na qual o parlamentar foi relator', null=True)),
                ('casa', models.TextField(help_text='Casa da etapa da proposição', null=True)),
                ('relator_id', models.IntegerField(help_text='Id do relator na casa de origem')),
                ('relator_id_parlametria', models.IntegerField(help_text='Id do autor no Parlametria')),
                ('relator_nome', models.TextField(help_text='Casa da etapa da proposição', null=True)),
                ('entidade', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='entidadeRelator', to='api.Entidade')),
                ('proposicao', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='relatoresProposicao', to='api.Proposicao')),
            ],
        ),
    ]
