# Generated by Django 3.1 on 2020-10-30 15:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0100_relatoresproposicao'),
    ]

    operations = [
        migrations.AddField(
            model_name='interesse',
            name='descricao_interesse',
            field=models.TextField(blank=True, help_text='Descrição do Interesse da Proposição', null=True),
        ),
    ]
