# Generated by Django 3.1 on 2020-12-17 15:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0101_interesse_descricao_interesse'),
    ]

    operations = [
        migrations.CreateModel(
            name='Destaques',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('id_leggo', models.TextField(help_text='Id interno do leggo.')),
                ('criterio_aprovada_em_uma_casa', models.BooleanField(blank=True, help_text='Matérias aprovadas em pelo menos uma das casas.', null=True)),
                ('casa_aprovacao', models.CharField(blank=True, max_length=6, null=True)),
                ('data_aprovacao', models.DateTimeField(blank=True, help_text='Data de finalização da proposição.', null=True)),
                ('criterio_avancou_comissoes', models.BooleanField(blank=True, null=True)),
                ('comissoes_camara', models.TextField(blank=True, null=True)),
                ('comissoes_senado', models.TextField(blank=True, null=True)),
            ],
        ),
    ]
