# Generated by Django 3.1 on 2020-12-15 15:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0101_interesse_descricao_interesse'),
    ]

    operations = [
        migrations.CreateModel(
            name='Destaques',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('id_leggo', models.TextField(help_text='Id interno do leggo.')),
                ('id_ext', models.IntegerField(help_text='Id externo do sistema da casa.')),
                ('casa', models.CharField(help_text='Casa desta proposição.', max_length=6)),
                ('sigla', models.TextField(help_text='Sigla da proposição na Câmara.')),
                ('criterio_aprovada_em_uma_casa', models.BooleanField(help_text='Foi aprovada no critério de matérias aprovadas em pelo menos uma das casas.')),
                ('fase_global', models.TextField(blank=True, null=True)),
                ('local', models.TextField(blank=True, null=True)),
                ('local_casa', models.CharField(blank=True, max_length=6, null=True)),
                ('data_inicio', models.DateTimeField(blank=True, help_text='Data de início da proposição.', null=True)),
                ('data_fim', models.DateTimeField(blank=True, help_text='Data de finalização da proposição.', null=True)),
                ('criterio_parecer_aprovado_comissao', models.BooleanField(help_text='Foi aprovada no critério de matérias com parecer aprovado em pelo menos uma comissão.')),
                ('comissoes_aprovadas', models.TextField(blank=True, help_text='Comissões em que a matéria foi aprovada.', null=True)),
                ('criterio_pressao_alta', models.BooleanField(help_text='Foi aprovada no critério .')),
                ('maximo_pressao_periodo', models.IntegerField(blank=True, help_text='Número máximo atingido pela pressão.', null=True)),
                ('agendas', models.TextField(help_text='Agendas que essa matéria está presente.')),
            ],
        ),
    ]
