# Generated by Django 3.0.7 on 2020-12-17 19:51

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0102_destaques'),
    ]

    operations = [
        migrations.AddField(
            model_name='destaques',
            name='proposicao',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='destaquesProposicao', to='api.Proposicao'),
        ),
    ]
