# Generated by Django 3.1 on 2020-12-18 17:12

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0102_destaques'),
    ]

    operations = [
        migrations.AddField(
            model_name='destaques',
            name='proposicao',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='destaques', to='api.proposicao'),
        ),
    ]
