# Generated by Django 3.1 on 2020-12-16 16:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0102_destaques'),
    ]

    operations = [
        migrations.AlterField(
            model_name='destaques',
            name='criterio_aprovada_em_uma_casa',
            field=models.BooleanField(help_text='Matérias aprovadas em pelo menos uma das casas.'),
        ),
        migrations.AlterField(
            model_name='destaques',
            name='criterio_parecer_aprovado_comissao',
            field=models.BooleanField(help_text='Matéria com parecer aprovado em pelo menos uma comissão.'),
        ),
        migrations.AlterField(
            model_name='destaques',
            name='criterio_pressao_alta',
            field=models.BooleanField(),
        ),
    ]
