# Generated by Django 3.0.7 on 2020-12-28 19:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0103_destaques_proposicao'),
    ]

    operations = [
        migrations.AddField(
            model_name='destaques',
            name='casa_origem',
            field=models.CharField(blank=True, help_text='Casa de origem da proposição', max_length=6, null=True),
        ),
        migrations.AddField(
            model_name='destaques',
            name='casa_req_urgencia_apresentado',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='destaques',
            name='casa_req_urgencia_aprovado',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='destaques',
            name='casa_revisora',
            field=models.CharField(blank=True, help_text='Casa revisora da proposição', max_length=6, null=True),
        ),
        migrations.AddField(
            model_name='destaques',
            name='criterio_req_urgencia_apresentado',
            field=models.BooleanField(blank=True, help_text='Matérias com requerimento de urgência apresentado.', null=True),
        ),
        migrations.AddField(
            model_name='destaques',
            name='criterio_req_urgencia_aprovado',
            field=models.BooleanField(blank=True, help_text='Matérias com requerimento de urgência aprovado.', null=True),
        ),
        migrations.AddField(
            model_name='destaques',
            name='data_req_urgencia_apresentado',
            field=models.DateTimeField(blank=True, help_text='Data de de apresentação do requerimento de urgência.', null=True),
        ),
        migrations.AddField(
            model_name='destaques',
            name='data_req_urgencia_aprovado',
            field=models.DateTimeField(blank=True, help_text='Data de de aprovação do requerimento de urgência', null=True),
        ),
    ]
