# Generated by Django 3.1 on 2020-12-16 17:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0103_auto_20201216_1640'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='destaques',
            name='comissoes_aprovadas',
        ),
        migrations.RemoveField(
            model_name='destaques',
            name='criterio_parecer_aprovado_comissao',
        ),
        migrations.AddField(
            model_name='destaques',
            name='ccj_camara',
            field=models.BooleanField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='destaques',
            name='criterio_avancou_comissoes',
            field=models.BooleanField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='destaques',
            name='parecer_aprovado_comissao',
            field=models.BooleanField(blank=True, help_text='Matéria com parecer aprovado em pelo menos uma comissão.', null=True),
        ),
    ]
