# Generated by Django 3.0.7 on 2021-01-06 14:09

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0104_auto_20201228_1924'),
    ]

    operations = [
        migrations.AddField(
            model_name='autoria',
            name='entidade',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='entidadeAutoria', to='api.Entidade'),
        ),
    ]
