# Generated by Django 3.1.1 on 2021-01-13 16:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0105_autoria_entidade'),
    ]

    operations = [
        migrations.AddField(
            model_name='autoria',
            name='sigla',
            field=models.TextField(help_text='Sigla do documento.', null=True),
        ),
    ]
