# Generated by Django 3.1.1 on 2021-01-28 11:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0106_autoria_sigla'),
    ]

    operations = [
        migrations.AlterField(
            model_name='infogerais',
            name='value',
            field=models.JSONField(),
        ),
    ]
