# Generated by Django 3.0.7 on 2021-02-19 14:22

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0107_auto_20210128_1300'),
    ]

    operations = [
        migrations.CreateModel(
            name='Governismo',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('id_parlamentar', models.IntegerField(help_text='Id do parlamentar', null=True)),
                ('id_parlamentar_parlametria', models.IntegerField(help_text='Id do parlamentar na plataforma parlametria', null=True)),
                ('casa', models.TextField(help_text='Casa do parlamentar', null=True)),
                ('governismo', models.FloatField(help_text='Valor do governismo', null=True)),
                ('entidade', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='entidadeGovernismo', to='api.Entidade')),
            ],
        ),
    ]
