# Generated by Django 3.1.1 on 2021-02-22 15:02

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0107_auto_20210128_1300'),
    ]

    operations = [
        migrations.CreateModel(
            name='Votacao',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('id_leggo', models.TextField(blank=True, help_text='Id interno do leggo.', null=True)),
                ('id_votacao', models.TextField(help_text='Id da votação nas APIs.')),
                ('data', models.DateField(blank=True, help_text='Data da votação.', null=True)),
                ('obj_votacao', models.TextField(help_text='Objeto de votação.')),
                ('casa', models.TextField(help_text='Casa.')),
                ('resumo', models.TextField(help_text='Resumo da votação.')),
                ('proposicao', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='votacoes', to='api.proposicao')),
            ],
        ),
    ]
