# Generated by Django 3.1.1 on 2021-02-22 17:09

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0108_votacao'),
    ]

    operations = [
        migrations.CreateModel(
            name='Voto',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('id_parlamentar', models.IntegerField(help_text='Id do parlamentar.', null=True)),
                ('id_parlamentar_parlametria', models.IntegerField(help_text='Id do parlamentar na plataforma parlametria.', null=True)),
                ('id_votacao', models.TextField(help_text='Id da votação nas APIs.')),
                ('partido', models.TextField(help_text='Partido do parlamentar.')),
                ('voto', models.TextField(help_text='Voto do parlamentar.')),
                ('casa', models.TextField(help_text='Casa do parlamentar.')),
                ('entidade', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='votoEntidade', to='api.entidade')),
                ('votacao', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='votoVotacao', to='api.votacao')),
            ],
        ),
    ]
