# Generated by Django 3.1 on 2021-03-01 17:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0109_votacao_voto'),
    ]

    operations = [
        migrations.AddField(
            model_name='votacao',
            name='is_nominal',
            field=models.BooleanField(help_text='Flag se a votação é nominal.', null=True),
        ),
    ]
