# Generated by Django 3.1.3 on 2021-03-16 15:29

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0111_auto_20210308_1606'),
    ]

    operations = [
        migrations.CreateModel(
            name='Disciplina',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('id_parlamentar', models.IntegerField(help_text='Id do parlamentar', null=True)),
                ('id_parlamentar_parlametria', models.IntegerField(help_text='Id do parlamentar na plataforma parlametria', null=True)),
                ('casa', models.TextField(help_text='Casa do parlamentar', null=True)),
                ('disciplina', models.FloatField(help_text='Valor do disciplina', null=True)),
                ('entidade', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='entidadeGovernismo', to='api.entidade')),
            ],
        ),
    ]
