# Generated by Django 3.1.3 on 2021-03-16 18:48

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0112_disciplina'),
    ]

    operations = [
        migrations.AlterField(
            model_name='disciplina',
            name='entidade',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='entidadeDisciplina', to='api.entidade'),
        ),
    ]
