# Generated by Django 3.1.4 on 2021-03-23 18:42

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0114_votacoessumarizadas'),
    ]

    operations = [
        migrations.AddField(
            model_name='votacoessumarizadas',
            name='entidade',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='entidadeVotacoesSumarizadas', to='api.entidade'),
        ),
        migrations.AlterField(
            model_name='votacoessumarizadas',
            name='num_votacoes_parlamentar_disciplina',
            field=models.IntegerField(help_text='Número de votações do parlamentar', null=True),
        ),
        migrations.AlterField(
            model_name='votacoessumarizadas',
            name='num_votacoes_parlamentar_governismo',
            field=models.IntegerField(help_text='Número de votações do parlamentar', null=True),
        ),
        migrations.AlterField(
            model_name='votacoessumarizadas',
            name='num_votacoes_totais_disciplina',
            field=models.IntegerField(help_text='Número de votações totais', null=True),
        ),
        migrations.AlterField(
            model_name='votacoessumarizadas',
            name='num_votacoes_totais_governismo',
            field=models.IntegerField(help_text='Número de votações totais', null=True),
        ),
    ]
