# Generated by Django 3.1.4 on 2021-03-24 14:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0115_auto_20210323_1842'),
    ]

    operations = [
        migrations.AddField(
            model_name='votacoessumarizadas',
            name='casa',
            field=models.TextField(help_text='Casa do parlamentar', null=True),
        ),
    ]
