# Generated by Django 3.1.4 on 2021-03-31 13:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0117_votacoessumarizadas_ultima_data_votacao'),
    ]

    operations = [
        migrations.AlterField(
            model_name='votacoessumarizadas',
            name='ultima_data_votacao',
            field=models.DateTimeField(help_text='Data da última votação', null=True),
        ),
    ]
