# Generated by Django 3.1.4 on 2021-03-31 13:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0118_auto_20210331_1342'),
    ]

    operations = [
        migrations.AlterField(
            model_name='votacoessumarizadas',
            name='ultima_data_votacao',
            field=models.DateField(help_text='Data da última votação', null=True),
        ),
    ]
