# Generated by Django 3.0.7 on 2021-03-31 19:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0119_auto_20210331_1347'),
    ]

    operations = [
        migrations.AddField(
            model_name='disciplina',
            name='bancada_suficiente',
            field=models.BooleanField(help_text='Se o partido tem bancada suficiente', null=True),
        ),
        migrations.AddField(
            model_name='disciplina',
            name='partido_atual',
            field=models.TextField(help_text='Partido atual do parlamentar', null=True),
        ),
        migrations.AddField(
            model_name='disciplina',
            name='partido_disciplina',
            field=models.TextField(help_text='Partido da disciplina', null=True),
        ),
        migrations.AlterField(
            model_name='votacoessumarizadas',
            name='ultima_data_votacao',
            field=models.DateTimeField(help_text='Data da última votação', null=True),
        ),
    ]
