# Generated by Django 3.0.7 on 2021-04-08 18:14

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0120_auto_20210331_1936'),
    ]

    operations = [
        migrations.CreateModel(
            name='LocalAtualProposicao',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('id_leggo', models.TextField(help_text='ID interno do Leggo')),
                ('sigla_ultimo_local', models.TextField(help_text='Sigla do último local da Proposição', null=True)),
                ('casa_ultimo_local', models.TextField(help_text='Casa do último local da Proposição', null=True)),
                ('nome_ultimo_local', models.TextField(help_text='Nome do último local da Proposição', null=True)),
                ('data_ultima_situacao', models.DateTimeField(help_text='Data da última situação registrada para a proposição', null=True)),
                ('tipo_local', models.TextField(help_text='Tipo do último local da proposição', null=True)),
                ('proposicao', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='locaisProposicao', to='api.Proposicao')),
            ],
        ),
    ]
