# Generated by Django 3.1.4 on 2021-04-15 14:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0120_auto_20210331_1936'),
    ]

    operations = [
        migrations.AddField(
            model_name='temperaturahistorico',
            name='id_leggo',
            field=models.TextField(help_text='Id da proposição principal no leggo.', null=True),
        ),
    ]
