# Generated by Django 3.1 on 2021-04-16 19:13

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0121_localatualproposicao'),
    ]

    operations = [
        migrations.CreateModel(
            name='ProposicaApensada',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('id_leggo', models.TextField(help_text='Id interno do leggo.', verbose_name='ID do Leggo')),
                ('id_leggo_prop_principal', models.TextField(blank=True, help_text='Id interno do leggo da proposição original.', null=True, verbose_name='ID do Leggo')),
                ('id_ext_prop_principal', models.IntegerField(blank=True, null=True, verbose_name='Id externo da proposição original na API da Câmara ou Senado')),
                ('casa_prop_principal', models.TextField(blank=True, null=True, verbose_name='Casa da proposição original onde houve a apensação')),
                ('proposicao_apensada', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='apensadas', to='api.proposicao')),
                ('proposicao_original', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='originais', to='api.proposicao')),
            ],
        ),
    ]
