# Generated by Django 3.0.7 on 2021-04-21 19:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0123_proposicaoapensada'),
    ]

    operations = [
        migrations.AddField(
            model_name='etapaproposicao',
            name='sigla',
            field=models.TextField(blank=True, help_text='Sigla da proposição', null=True, verbose_name='Sigla da proposição'),
        ),
    ]
