# Generated by Django 3.0.7 on 2021-04-26 17:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0124_etapaproposicao_sigla'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='etapaproposicao',
            name='autor_nome',
        ),
        migrations.RemoveField(
            model_name='etapaproposicao',
            name='autor_partido',
        ),
        migrations.RemoveField(
            model_name='etapaproposicao',
            name='autor_uf',
        ),
    ]
