# Generated by Django 3.0.7 on 2021-05-04 14:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0125_auto_20210426_1757'),
    ]

    operations = [
        migrations.AddField(
            model_name='proposicaoapensada',
            name='id_ext_prop_principal_raiz',
            field=models.IntegerField(blank=True, null=True, verbose_name='Id externo da proposição principal raiz na API da Câmara ou Senado'),
        ),
        migrations.AlterField(
            model_name='proposicaoapensada',
            name='casa_prop_principal',
            field=models.TextField(blank=True, null=True, verbose_name='Casa da proposição principal raiz onde houve a apensação'),
        ),
        migrations.AlterField(
            model_name='proposicaoapensada',
            name='id_ext_prop_principal',
            field=models.IntegerField(blank=True, null=True, verbose_name='Id externo da proposição principal na API da Câmara ou Senado'),
        ),
        migrations.AlterField(
            model_name='proposicaoapensada',
            name='id_leggo_prop_principal',
            field=models.TextField(blank=True, help_text='Id interno da proposição principal raiz.', null=True, verbose_name='ID do Leggo'),
        ),
    ]
