# Generated by Django 3.1 on 2021-05-17 13:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0126_auto_20210504_1439'),
    ]

    operations = [
        migrations.AddField(
            model_name='pressao',
            name='sum_interactions',
            field=models.IntegerField(default=0, verbose_name='Soma de interações nos tweets'),
        ),
        migrations.AddField(
            model_name='pressao',
            name='user_count',
            field=models.IntegerField(default=0, verbose_name='Quantidade de usuários tweetando sobre uma proposição'),
        ),
    ]
