# Generated by Django 3.2.13 on 2022-06-13 18:59

from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
        ('usuario', '0002_perfil'),
    ]

    operations = [
        migrations.CreateModel(
            name='VerfificacaoEmail',
            fields=[
                ('usuario', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, related_name='verificacao_email', serialize=False, to='auth.user')),
                ('token', models.UUIDField(default=uuid.uuid4)),
                ('verificado', models.BooleanField(default=False)),
            ],
        ),
    ]
