# Generated by Django 3.2.13 on 2022-07-11 21:58

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    replaces = [('tweets', '0001_initial'), ('tweets', '0002_auto_20220503_1640'), ('tweets', '0003_alter_perfil_twitter_id'), ('tweets', '0004_alter_tweet_id_tweet'), ('tweets', '0005_auto_20220504_1820'), ('tweets', '0006_alter_perfil_tweets'), ('tweets', '0007_alter_perfil_tweets'), ('tweets', '0008_auto_20220505_1430'), ('tweets', '0009_rename_tweets_tweet_author'), ('tweets', '0010_auto_20220505_1535'), ('tweets', '0011_pressao'), ('tweets', '0012_alter_pressao_data_consulta'), ('tweets', '0013_engajamento'), ('tweets', '0014_engajamento_proposicao'), ('tweets', '0015_pressao_total_likes'), ('tweets', '0016_alter_tweet_text'), ('tweets', '0017_engajamento_tid_author'), ('tweets', '0018_alter_engajamento_perfil'), ('tweets', '0019_auto_20220516_1830'), ('tweets', '0020_auto_20220517_1440'), ('tweets', '0021_rename_perfil_parlamentarperfil'), ('tweets', '0022_auto_20220601_1609'), ('tweets', '0023_tweetsinfo'), ('tweets', '0024_rename_tweet_mais_antido_tweetsinfo_tweet_mais_antigo'), ('tweets', '0025_alter_pressao_proposicao'), ('tweets', '0026_auto_20220613_2149'), ('tweets', '0027_tweetsinteresse'), ('tweets', '0028_rename_nome_tweetsinteresse_interesse_unico'), ('tweets', '0029_delete_tweetsinteresse'), ('tweets', '0030_alter_engajamentoproposicao_data_consulta'), ('tweets', '0031_alter_pressao_data_consulta')]

    initial = True

    dependencies = [
        ('api', '0127_auto_20210517_1358'),
    ]

    operations = [
         migrations.CreateModel(
            name='ParlamentarPerfil',
            fields=[
                ('is_personalidade', models.BooleanField()),
                ('name', models.CharField(max_length=150)),
                ('entidade', models.OneToOneField(default=-1, on_delete=django.db.models.deletion.CASCADE, primary_key=True, related_name='entidadePerfil', serialize=False, to='api.entidade')),
                ('twitter_id', models.CharField(default=None, max_length=40, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Tweet',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('id_tweet', models.CharField(default=0, max_length=40)),
                ('text', models.TextField()),
                ('data_criado', models.DateField()),
                ('likes', models.IntegerField()),
                ('retweets', models.IntegerField()),
                ('respostas', models.IntegerField()),
                ('proposicao', models.ManyToManyField(to='api.Proposicao')),
                ('author', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='author', to='tweets.parlamentarPerfil')),
                ('id_author', models.CharField(default=0, max_length=40)),
                ('text_html', models.TextField(default='')),
            ],
        ),
        migrations.CreateModel(
            name='TweetsInfo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('numero_total_tweets', models.IntegerField()),
                ('numero_parlamentares_sem_perfil', models.IntegerField()),
                ('tweet_mais_antigo', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='antigo', to='tweets.tweet')),
                ('tweet_mais_novo', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='novo', to='tweets.tweet')),
            ],
        ),
        migrations.CreateModel(
            name='Pressao',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('total_tweets', models.IntegerField()),
                ('total_usuarios', models.IntegerField()),
                ('total_engajamento', models.IntegerField()),
                ('data_consulta', models.DateField()),
                ('proposicao', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='pressao_intervalo', to='api.proposicao')),
                ('total_likes', models.IntegerField(default=0)),
            ],
        ),
        migrations.CreateModel(
            name='EngajamentoProposicao',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('data_consulta', models.DateField()),
                ('total_engajamento', models.IntegerField()),
                ('perfil', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='tweets.parlamentarPerfil')),
                ('proposicao', models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='api.proposicao')),
                ('tid_author', models.CharField(default=0, max_length=40)),
            ],
        ),
    ]
