# Generated by Django 3.2.13 on 2022-07-12 13:48

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0127_auto_20210517_1358'),
        ('tweets', '0001_squashed_0031_alter_pressao_data_consulta'),
    ]

    operations = [
        migrations.AlterField(
            model_name='parlamentarperfil',
            name='entidade',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, related_name='entidadePerfil', serialize=False, to='api.entidade'),
        ),
        migrations.AlterField(
            model_name='tweet',
            name='text_html',
            field=models.TextField(),
        ),
    ]
