# Generated by Django 3.2.13 on 2022-07-22 21:48

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    replaces = [('tweets', '0003_auto_20220722_1934'), ('tweets', '0004_auto_20220722_1954')]

    dependencies = [
        ('api', '0127_auto_20210517_1358'),
        ('tweets', '0002_auto_20220712_1348'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tweetsinfo',
            name='tweet_mais_antigo',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='antigo', to='api.entidade'),
        ),
        migrations.AlterField(
            model_name='tweetsinfo',
            name='tweet_mais_novo',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='novo', to='api.entidade'),
        ),
        migrations.AlterField(
            model_name='tweetsinfo',
            name='tweet_mais_antigo',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='antigo', to='tweets.tweet'),
        ),
        migrations.AlterField(
            model_name='tweetsinfo',
            name='tweet_mais_novo',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='novo', to='tweets.tweet'),
        ),
    ]
